// Menu dataset redesigned for Lala Hoti Lal Halwai & Cafe
const DEFAULT_MENU_DATA = {
  cartName: "Lala Hoti Lal Halwai & Cafe",
  tagline: "Pure Veg Artisanal Street Eats, Snacks & Cafe Favorites 🌱",
  location: "Pure Veg Station • Cart #04",
  hours: "Open Daily: 10:00 AM - 10:00 PM",
  adminPin: "1234",
  currency: "₹",
  categories: [
    { id: "all", name: "All Items", icon: "✨" },
    { id: "chai-coffee", name: "Chai & Coffee", icon: "☕" },
    { id: "snacks", name: "Snacks & Chaat", icon: "🍿" },
    { id: "puffs", name: "Puff Patties", icon: "🥐" },
    { id: "momos", name: "Momos Special", icon: "🥟" },
    { id: "burgers", name: "Burgers", icon: "🍔" },
    { id: "maggi", name: "Maggi Special", icon: "🍜" },
    { id: "sandwiches", name: "Grilled Sandwiches", icon: "🥪" },
    { id: "pasta-fries", name: "Pasta & Fries", icon: "🍟" },
    { id: "beverages", name: "Shakes & Coolers", icon: "🧋" }
  ],
  items: [
    // --- TEA / COFFEE ---
    {
      id: "pdf-1",
      name: "Black Tea",
      category: "chai-coffee",
      price: 10,
      description: "Refreshing aromatic black tea infused with cardamom and ginger.",
      image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Hot ☕"],
      dietary: ["vegetarian", "vegan"],
      calories: "25 kcal"
    },
    {
      id: "pdf-2",
      name: "Black Coffee",
      category: "chai-coffee",
      price: 20,
      description: "Rich dark roasted espresso style black coffee.",
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Strong ☕"],
      dietary: ["vegetarian", "vegan"],
      calories: "10 kcal"
    },
    {
      id: "pdf-3",
      name: "Kullhad Chai",
      category: "chai-coffee",
      price: 15,
      description: "Traditional clay-pot steamed masala chai with earthy flavor.",
      image: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Bestseller 🔥", "Traditional"],
      dietary: ["vegetarian"],
      calories: "60 kcal"
    },
    {
      id: "pdf-4",
      name: "Special Masala Chai",
      category: "chai-coffee",
      price: 25,
      description: "House special spiced tea brewed with fresh milk, lemongrass, tulsi, and saffron spices.",
      image: "https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Chef Special ⭐"],
      dietary: ["vegetarian"],
      calories: "85 kcal"
    },
    {
      id: "pdf-5",
      name: "Hot Coffee",
      category: "chai-coffee",
      price: 25,
      description: "Frothy whipped milk hot coffee with chocolate dusting.",
      image: "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Frothy ☕"],
      dietary: ["vegetarian"],
      calories: "110 kcal"
    },

    // --- SNACKS ---
    {
      id: "pdf-6",
      name: "Vegetable Noodles",
      category: "snacks",
      price: 30,
      halfPrice: 20,
      description: "Desi chowmein wok-tossed with crunchy vegetables and tangy soy garlic sauce (Half ₹20 / Full ₹30).",
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Desi Style 🍜"],
      dietary: ["vegetarian"],
      calories: "280 kcal"
    },
    {
      id: "pdf-7",
      name: "Vada Pav (Single / Double)",
      category: "snacks",
      price: 30,
      offerQty: 2,
      offerPrice: 50,
      description: "Mumbai street style fried potato vada tucked inside soft pav with spicy garlic chutney (1 Pc ₹30 / 2 Pcs ₹50).",
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Mumbai Special 🔥", "Spicy 🌶️"],
      dietary: ["vegetarian", "spicy"],
      calories: "240 kcal"
    },
    {
      id: "pdf-8",
      name: "Veg Spring Roll",
      category: "snacks",
      price: 25,
      offerQty: 2,
      offerPrice: 40,
      description: "Crispy fried rolls filled with seasoned shredded cabbage, carrots, and glass noodles (1 Pc ₹25 / 2 Pcs ₹40).",
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Crispy 🥖"],
      dietary: ["vegetarian"],
      calories: "210 kcal"
    },
    {
      id: "pdf-9",
      name: "Kurkura Roll",
      category: "snacks",
      price: 35,
      offerQty: 2,
      offerPrice: 60,
      description: "Extra crunchy corn-flake crusted veg roll served with spicy mayo dip (1 Pc ₹35 / 2 Pcs ₹60).",
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Super Crunch ⭐"],
      dietary: ["vegetarian"],
      calories: "290 kcal"
    },
    {
      id: "pdf-10",
      name: "Special Soya Chaap",
      category: "snacks",
      price: 30,
      offerQty: 2,
      offerPrice: 50,
      description: "Tandoori marinated soya chaap grilled on skewer with mint chutney (1 Pc ₹30 / 2 Pcs ₹50).",
      image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Tandoori 🔥"],
      dietary: ["vegetarian"],
      calories: "320 kcal"
    },
    {
      id: "pdf-11",
      name: "Butter Pav Bhaji (2/4 Pcs)",
      category: "snacks",
      price: 70,
      description: "Rich butter-laden spicy mashed vegetable bhaji served with butter toasted pav, lemon, and onions.",
      image: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Bestseller 🔥", "Butter Rich"],
      dietary: ["vegetarian"],
      calories: "450 kcal"
    },
    {
      id: "pdf-12",
      name: "Chilli Potato",
      category: "snacks",
      price: 90,
      description: "Crispy fried potato fingers tossed in spicy sweet chili garlic sauce with sesame seeds.",
      image: "https://images.unsplash.com/photo-1518013431117-eb1465fa5752?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Spicy 🌶️", "Indo-Chinese"],
      dietary: ["vegetarian", "spicy"],
      calories: "380 kcal"
    },

    // --- PUFF SPECIAL ---
    {
      id: "pdf-13",
      name: "Simple Patties",
      category: "puffs",
      price: 15,
      description: "Golden flaky puff pastry stuffed with spiced potato filling.",
      image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Extra Cheese +₹30 Option"],
      dietary: ["vegetarian"],
      calories: "180 kcal"
    },
    {
      id: "pdf-14",
      name: "Namkeen Patties",
      category: "puffs",
      price: 25,
      description: "Crispy puff stuffed with savory namkeen mix and tangy green chutney.",
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Extra Cheese +₹30 Option"],
      dietary: ["vegetarian"],
      calories: "210 kcal"
    },
    {
      id: "pdf-15",
      name: "Butter Patties",
      category: "puffs",
      price: 30,
      description: "Rich flaky puff pastry warmed with melted Amul butter.",
      image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Butter Loaded", "Extra Cheese +₹30"],
      dietary: ["vegetarian"],
      calories: "260 kcal"
    },
    {
      id: "pdf-16",
      name: "Paneer Patties",
      category: "puffs",
      price: 35,
      description: "Puff stuffed with seasoned cottage cheese paneer cubes and herbs.",
      image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Paneer Rich 🧀", "Extra Cheese +₹30"],
      dietary: ["vegetarian"],
      calories: "290 kcal"
    },
    {
      id: "pdf-17",
      name: "Cheese Patties",
      category: "puffs",
      price: 40,
      description: "Ooze-filled puff loaded with melted mozzarella & cheddar cheese blend.",
      image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Cheesy 🧀", "Popular 🔥"],
      dietary: ["vegetarian"],
      calories: "320 kcal"
    },
    {
      id: "pdf-18",
      name: "Pizza Patties",
      category: "puffs",
      price: 70,
      description: "Special puff stuffed with pizza sauce, sweet corn, capsicum, olives, and double mozzarella cheese.",
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Chef Special ⭐", "Pizza Loaded"],
      dietary: ["vegetarian"],
      calories: "410 kcal"
    },

    // --- MOMOS SPECIAL ---
    {
      id: "pdf-19",
      name: "Veggie Steamed Momos",
      category: "momos",
      price: 60,
      halfPrice: 30,
      description: "Soft steamed dumplings stuffed with minced cabbage, carrots, onion & garlic (6 Pcs Half ₹30 / 12 Pcs Full ₹60).",
      image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Steamed 🥟", "Healthy Option"],
      dietary: ["vegetarian", "vegan"],
      calories: "180 kcal"
    },
    {
      id: "pdf-20",
      name: "Veggie Fried Momos",
      category: "momos",
      price: 60,
      halfPrice: 30,
      description: "Golden crisp fried vegetable momos served with fiery red chutney (5 Pcs Half ₹30 / 10 Pcs Full ₹60).",
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Crispy Fried 🥟"],
      dietary: ["vegetarian"],
      calories: "260 kcal"
    },
    {
      id: "pdf-21",
      name: "Veggie Kurkure Momos",
      category: "momos",
      price: 90,
      halfPrice: 50,
      description: "Crunchy batter-coated and crushed cornflake crust veggie momos (4 Pcs Half ₹50 / 8 Pcs Full ₹90).",
      image: "https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Super Kurkure 🔥"],
      dietary: ["vegetarian"],
      calories: "340 kcal"
    },
    {
      id: "pdf-22",
      name: "Paneer Steamed Momos",
      category: "momos",
      price: 90,
      halfPrice: 50,
      description: "Steamed momos stuffed with spiced grated paneer cottage cheese (5 Pcs Half ₹50 / 10 Pcs Full ₹90).",
      image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Paneer Loaded 🧀"],
      dietary: ["vegetarian"],
      calories: "240 kcal"
    },
    {
      id: "pdf-23",
      name: "Paneer Fried Momos",
      category: "momos",
      price: 90,
      halfPrice: 50,
      description: "Golden crispy fried paneer momos served with mayonnaise dip (5 Pcs Half ₹50 / 10 Pcs Full ₹90).",
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Crispy Paneer"],
      dietary: ["vegetarian"],
      calories: "310 kcal"
    },
    {
      id: "pdf-24",
      name: "Paneer Kurkure Momos (4/8 Pcs)",
      category: "momos",
      price: 75,
      description: "Signature crunchy cornflake crusted paneer momos loaded with spicy dips (4 Pcs ₹75 / 8 Pcs ₹120).",
      image: "https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Chef Special ⭐", "Must Try 🔥"],
      dietary: ["vegetarian"],
      calories: "390 kcal"
    },

    // --- BURGERS ---
    {
      id: "pdf-25",
      name: "Simple Aloo Burger",
      category: "burgers",
      price: 25,
      description: "Crispy aloo tikki patty with fresh onion, tomato, and tangy burger sauce (Single ₹25 / Double ₹40).",
      image: "https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Classic Aloo", "Extra Cheese +₹30"],
      dietary: ["vegetarian"],
      calories: "290 kcal"
    },
    {
      id: "pdf-26",
      name: "Mayo Aloo Burger",
      category: "burgers",
      price: 35,
      description: "Golden aloo tikki loaded with creamy garlic mayonnaise and crisp lettuce (Single ₹35 / Double ₹60).",
      image: "https://images.unsplash.com/photo-1521305916504-4a1121188589?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Creamy Mayo", "Extra Cheese +₹30"],
      dietary: ["vegetarian"],
      calories: "340 kcal"
    },
    {
      id: "pdf-27",
      name: "Simple Paneer Burger",
      category: "burgers",
      price: 40,
      description: "Grilled paneer slab patty with spices and special sauce (Single ₹40 / Double ₹70).",
      image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Paneer Loaded 🧀", "Extra Cheese +₹30"],
      dietary: ["vegetarian"],
      calories: "360 kcal"
    },
    {
      id: "pdf-28",
      name: "Cheesy Aloo Burger",
      category: "burgers",
      price: 50,
      description: "Crispy aloo tikki with melted cheddar cheese slice and spicy jalapeño sauce (Single ₹50 / Double ₹90).",
      image: "https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Double Cheese 🧀", "Popular 🔥"],
      dietary: ["vegetarian"],
      calories: "420 kcal"
    },
    {
      id: "pdf-29",
      name: "Cheesy Paneer Burger",
      category: "burgers",
      price: 60,
      description: "Thick paneer patty layered with melted cheese slice and smoky thousand island spread (Single ₹60 / Double ₹110).",
      image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Bestseller 🔥", "Ultimate Cheese"],
      dietary: ["vegetarian"],
      calories: "480 kcal"
    },

    // --- MAGGI SPECIAL ---
    {
      id: "pdf-30",
      name: "Plain Maggi",
      category: "maggi",
      price: 40,
      description: "Classic comforting 2-minute classic Maggi noodles.",
      image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Extra Veggies +₹20"],
      dietary: ["vegetarian"],
      calories: "220 kcal"
    },
    {
      id: "pdf-31",
      name: "Masala Maggi",
      category: "maggi",
      price: 50,
      description: "Spicy Maggi cooked with special roasted indian spices and green chilies.",
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Spicy 🌶️", "Extra Veggies +₹20"],
      dietary: ["vegetarian", "spicy"],
      calories: "250 kcal"
    },
    {
      id: "pdf-32",
      name: "Butter Maggi",
      category: "maggi",
      price: 50,
      description: "Maggi tossed with generous dollop of Amul butter and oregano.",
      image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Butter Rich", "Extra Veggies +₹20"],
      dietary: ["vegetarian"],
      calories: "290 kcal"
    },
    {
      id: "pdf-33",
      name: "Vegetable Maggi",
      category: "maggi",
      price: 60,
      description: "Maggi loaded with crunchy sweet corn, green peas, carrots, and capsicum.",
      image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Veggie Loaded 🥦"],
      dietary: ["vegetarian"],
      calories: "280 kcal"
    },
    {
      id: "pdf-34",
      name: "Cheese Maggi",
      category: "maggi",
      price: 70,
      description: "Hot Maggi topped with grated cheddar cheese melting over the noodles.",
      image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Cheesy 🧀", "Popular 🔥"],
      dietary: ["vegetarian"],
      calories: "340 kcal"
    },
    {
      id: "pdf-35",
      name: "Cheese & Creamy Maggi",
      category: "maggi",
      price: 90,
      description: "Ultra rich Maggi cooked in white cream sauce, double cheese, herbs, and butter.",
      image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281292?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Chef Special ⭐", "Super Creamy"],
      dietary: ["vegetarian"],
      calories: "430 kcal"
    },

    // --- GRILLED SANDWICH ---
    {
      id: "pdf-36",
      name: "Cheese Grilled Sandwich",
      category: "sandwiches",
      price: 40,
      description: "Butter toasted bread filled with melted cheese blend and oregano spices.",
      image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Extra Cheese +₹30 Option"],
      dietary: ["vegetarian"],
      calories: "280 kcal"
    },
    {
      id: "pdf-37",
      name: "Bombay Aloo Grilled Sandwich",
      category: "sandwiches",
      price: 40,
      description: "Street style potato masala, cucumber, tomato, and mint chutney grilled sandwich.",
      image: "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Bombay Style 🔥"],
      dietary: ["vegetarian"],
      calories: "310 kcal"
    },
    {
      id: "pdf-38",
      name: "Classic Paneer Grilled Sandwich",
      category: "sandwiches",
      price: 50,
      description: "Fresh cottage cheese paneer cubes with veggies and butter grilled.",
      image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Paneer Loaded 🧀"],
      dietary: ["vegetarian"],
      calories: "340 kcal"
    },
    {
      id: "pdf-39",
      name: "Chilli Paneer Grilled Sandwich",
      category: "sandwiches",
      price: 50,
      description: "Spicy Indo-Chinese style paneer capsicum filling in crunchy grilled bread.",
      image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Spicy 🌶️", "Indo-Chinese"],
      dietary: ["vegetarian", "spicy"],
      calories: "350 kcal"
    },
    {
      id: "pdf-40",
      name: "Spicy Paneer Grilled Sandwich",
      category: "sandwiches",
      price: 50,
      description: "Paneer seasoned with peri-peri & red chili flakes grilled to perfection.",
      image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Spicy 🌶️"],
      dietary: ["vegetarian", "spicy"],
      calories: "350 kcal"
    },
    {
      id: "pdf-41",
      name: "Corn Mayo Grilled Sandwich",
      category: "sandwiches",
      price: 50,
      description: "Sweet corn tossed in rich garlic mayonnaise and black pepper spread.",
      image: "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Sweet Corn 🌽"],
      dietary: ["vegetarian"],
      calories: "330 kcal"
    },
    {
      id: "pdf-42",
      name: "Cheese Corn Grilled Sandwich",
      category: "sandwiches",
      price: 70,
      description: "Golden sweet corn combined with heavy mozzarella cheese and herbs.",
      image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Bestseller 🔥", "Extra Cheesy"],
      dietary: ["vegetarian"],
      calories: "410 kcal"
    },
    {
      id: "pdf-43",
      name: "Cheese Corn Potato Sandwich",
      category: "sandwiches",
      price: 75,
      description: "Triple filling of spiced potato, sweet corn, melted cheese & butter grill.",
      image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Chef Special ⭐", "Loaded"],
      dietary: ["vegetarian"],
      calories: "440 kcal"
    },

    // --- PASTA & FRIES ---
    {
      id: "pdf-44",
      name: "Alfredo White Sauce Pasta",
      category: "pasta-fries",
      price: 90,
      description: "Penne pasta cooked in velvety butter white cream sauce, garlic, and parmesan.",
      image: "https://images.unsplash.com/photo-1621996346565-e3d5d6281292?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Creamy Alfredo 🍝"],
      dietary: ["vegetarian"],
      calories: "460 kcal"
    },
    {
      id: "pdf-45",
      name: "Mix Sauce Pink Pasta",
      category: "pasta-fries",
      price: 109,
      description: "Combination of rich tangy red arrabbiata sauce and creamy white sauce with herbs.",
      image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Chef Special ⭐", "Pink Sauce"],
      dietary: ["vegetarian"],
      calories: "490 kcal"
    },
    {
      id: "pdf-46",
      name: "Salted French Fries",
      category: "pasta-fries",
      price: 50,
      description: "Golden fried potato fries lightly salted, served with tomato ketchup.",
      image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Classic 🍟"],
      dietary: ["vegetarian", "vegan"],
      calories: "280 kcal"
    },
    {
      id: "pdf-47",
      name: "Peri-Peri French Fries",
      category: "pasta-fries",
      price: 50,
      description: "Crispy fries tossed in spicy African peri-peri seasoning.",
      image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Spicy 🌶️", "Bestseller 🔥"],
      dietary: ["vegetarian", "spicy"],
      calories: "290 kcal"
    },
    {
      id: "pdf-48",
      name: "Tandoori French Fries",
      category: "pasta-fries",
      price: 50,
      description: "Fries dusted with smoky Indian tandoori masala and dip.",
      image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Tandoori Masala"],
      dietary: ["vegetarian"],
      calories: "290 kcal"
    },
    {
      id: "pdf-49",
      name: "Cheese Loaded French Fries",
      category: "pasta-fries",
      price: 90,
      description: "Crispy fries smothered in warm liquid cheese sauce and grated cheddar.",
      image: "https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Cheese Overload 🧀"],
      dietary: ["vegetarian"],
      calories: "450 kcal"
    },

    // --- BEVERAGES & COOLERS ---
    {
      id: "pdf-50",
      name: "Cold Coffee",
      category: "beverages",
      price: 60,
      description: "Thick chilled whipped coffee milk with chocolate syrup drizzle.",
      image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Chilled 🧋", "Bestseller 🔥"],
      dietary: ["vegetarian"],
      calories: "210 kcal"
    },
    {
      id: "pdf-51",
      name: "Hazelnut Cold Coffee",
      category: "beverages",
      price: 75,
      description: "Chilled cold coffee blended with nutty roasted hazelnut flavor.",
      image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Hazelnut 🌰"],
      dietary: ["vegetarian"],
      calories: "250 kcal"
    },
    {
      id: "pdf-52",
      name: "Chocolate Shake",
      category: "beverages",
      price: 70,
      description: "Thick creamy milk chocolate shake topped with chocolate chips.",
      image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Rich Chocolate 🍫"],
      dietary: ["vegetarian"],
      calories: "320 kcal"
    },
    {
      id: "pdf-53",
      name: "Oreo Shake",
      category: "beverages",
      price: 70,
      description: "Thick milkshake blended with crunchy Oreo cookies and vanilla ice cream.",
      image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Oreo Crunch 🍪", "Popular 🔥"],
      dietary: ["vegetarian"],
      calories: "360 kcal"
    },
    {
      id: "pdf-54",
      name: "Soda Shikanji",
      category: "beverages",
      price: 40,
      description: "Desi fizzy lemon soda flavored with roasted cumin black salt.",
      image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Refreshing 🍋"],
      dietary: ["vegetarian", "vegan"],
      calories: "80 kcal"
    },
    {
      id: "pdf-55",
      name: "Nimbu Masala Cooler",
      category: "beverages",
      price: 40,
      description: "Tangy Indian lemonade with chatpata spices and crushed ice.",
      image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: false,
      tags: ["Chatpata 🍋"],
      dietary: ["vegetarian", "vegan"],
      calories: "70 kcal"
    },
    {
      id: "pdf-56",
      name: "Virgin Mojito",
      category: "beverages",
      price: 70,
      description: "Refreshing fizzy mocktail with fresh mint leaves, lemon wedges, and crushed ice.",
      image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Mint Fresh 🍃"],
      dietary: ["vegetarian", "vegan"],
      calories: "120 kcal"
    },
    {
      id: "pdf-57",
      name: "Polo Mint Mojito",
      category: "beverages",
      price: 70,
      description: "Cooling Polo peppermint infused soda mojito with lemon lime flavor.",
      image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
      inStock: true,
      popular: true,
      tags: ["Extra Cool ❄️"],
      dietary: ["vegetarian", "vegan"],
      calories: "110 kcal"
    }
  ]
};
